#!/bin/bash
# Build a double-clickable "Agent Office.app" that runs scripts/start.sh.
# Usage: ./scripts/make-app.sh [path/to/Agent Office.app]
#
# Why generate it here instead of committing an .app: an .app that arrives over
# the network is quarantined, and Gatekeeper refuses to open it unless it is
# signed and notarised ("developer cannot be verified"). One built on the machine
# it runs on carries no quarantine flag and simply opens. So this stays a
# generator — zip the result and mail it and it becomes unopenable; send the repo
# and this script instead.
set -euo pipefail

REPO="$(cd "$(dirname "$0")/.." && pwd)"
APP="${1:-$HOME/Applications/Agent Office.app}"

# An app launched from Finder gets a bare PATH — /usr/bin:/bin:/usr/sbin:/sbin —
# so `npm` (living under ~/.nvm/versions/node/*/bin) is simply not found and the
# icon does nothing at all. install-daemon-service.sh learned this against launchd
# and bakes the absolute path into the plist; same trick, same reason.
NPM_BIN="$(dirname "$(command -v npm)")"

rm -rf "$APP"
mkdir -p "$APP/Contents/MacOS"

cat > "$APP/Contents/Info.plist" << 'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>CFBundleName</key><string>Agent Office</string>
  <key>CFBundleDisplayName</key><string>Agent Office</string>
  <key>CFBundleIdentifier</key><string>com.agentoffice.launcher</string>
  <key>CFBundleVersion</key><string>1.0</string>
  <key>CFBundlePackageType</key><string>APPL</string>
  <key>CFBundleExecutable</key><string>agent-office</string>
  <!-- no Dock icon: this opens a browser tab and exits, it is not an app you
       switch to. Without it you get a bouncing icon that never settles. -->
  <key>LSUIElement</key><true/>
</dict>
</plist>
EOF

cat > "$APP/Contents/MacOS/agent-office" << EOF
#!/bin/bash
# Generated by scripts/make-app.sh — edit that, not this.
export PATH="$NPM_BIN:\$PATH"
LOG="\$HOME/Library/Logs/agent-office-app.log"
# The build takes a few seconds and a launcher with no Dock icon is otherwise
# completely silent — say something before the wait, not after it.
osascript -e 'display notification "Đang dựng văn phòng…" with title "Agent Office"'
if "$REPO/scripts/start.sh" >> "\$LOG" 2>&1; then
  exit 0
fi
osascript -e 'display alert "Agent Office không mở được" message "Xem log: ~/Library/Logs/agent-office-app.log"'
exit 1
EOF
chmod +x "$APP/Contents/MacOS/agent-office"

echo "created: $APP"
echo "run it:  open \"$APP\"   (or double-click it in Finder)"
